"""anchor_url column in embeddings db

Revision ID: de6ed5a2200a
Revises: 0fd17e9eddb9
Create Date: 2023-03-08 12:51:11.462919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6ed5a2200a'
down_revision = '0fd17e9eddb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('anchor_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'anchor_url')
    # ### end Alembic commands ###
