"""add content_type as additional table column

Revision ID: ff2a3643c6db
Revises: de6ed5a2200a
Create Date: 2023-03-08 16:01:00.780690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2a3643c6db'
down_revision = 'de6ed5a2200a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'content_type')
    # ### end Alembic commands ###
